name: mmastats

on:
  push:
    branches: [ feature/eslint ]
  pull_request:
    branches: [ master ]

jobs:
  mmmastats_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint